apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: GitRepository
metadata:
  name: helm-hello
  namespace: helm-hello
spec:
  interval: 1m0s
  ref:
    branch: main
  url: 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-hello
  namespace: helm-hello
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart/hello/
      version: "1.0"
      sourceRef:
        kind: GitRepository
        name: helm-hello
        namespace: helm-hello
      interval: 1m
